name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "environments/**"
      - "modules/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    if: github.head_ref == 'dev'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::277052498943:role/GitHubTerraformPlanRole
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform initialise
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -no-color
